name: Compilazione Automatica CostyCNC

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Scarica il codice sorgente
      uses: actions/checkout@v4

    - name: Configura MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Configura NuGet
      uses: NuGet/setup-nuget@v2

    - name: Ripristina i pacchetti NuGet
      run: nuget restore LaserGRBL.sln

    - name: Compila solo l'eseguibile principale
      run: msbuild LaserGRBL/LaserGRBL.csproj /p:Configuration=Release /p:Platform="AnyCPU"

    - name: Salva e rendi scaricabile il file EXE compilato
      uses: actions/upload-artifact@v4
      with:
        name: LaserGRBL-CostyCNC
        path: LaserGRBL/bin/Release/
